apiVersion: v1
kind: ConfigMap
metadata: 
 name: backend
 namespace: expense
data:
 DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: api
    project: expense
spec:
  # modify replicas according to your case
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: backend
      tier: api
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: api
        project: expense
    spec:
      containers:
      - name:  backend
        image: shirisha02/backend:v1
        resources:
          requests:
            memory: "100Mi"
            cpu: "120m"
          limits:
            memory: "128Mi"
            cpu: "120m"
        envFrom:
        - configMapRef:
            name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: api
    project: expense
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080
    targetPort: 8080 
---
apiVersion: autoscaling/v1
#apiVersion: autoscaling/v2beta2  # k8s 1.6+ - scale using the largest of multiple metrics
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  namespace: expense
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: {{ .Values.hpa.cpuUtilization }} # by default in real time utilization percentage is 75         